#!/usr/bin/env bash

"${UMBREL_ROOT}/scripts/app" start lightning
"${UMBREL_ROOT}/scripts/app" start lnbits

UMBREL_HOST=$(echo $(hostname -s 2>/dev/null)".local")
LNBITS_URL="http://${UMBREL_HOST}:3007"

echo "Waiting for lnbits to be available ..."
for attempt in $(seq 1 600); do
    (curl $LNBITS_URL &> /dev/null)
    if [[ "$?" -eq 0 ]]; then
        break
    fi
    sleep 0.1
done

(curl $LNBITS_URL &> /dev/null)
if [[ ! "$?" -eq 0 ]]; then
    echo "Lnbits not available."
    exit
fi

echo "Lnbits is available."